Jobsway2go.WebUI/Controllers/GroupController.cs
using Jobsway2go.Core.Interfaces;
using Jobsway2go.Core.Models;
using Microsoft.AspNetCore.Mvc;

namespace Jobsway2go.WebUI.Controllers
{
    public class GroupController : Controller
    {
        private readonly IGroupService _groupService;
        public GroupController ( IGroupService groupService)
        {
            _groupService = groupService;
        }

        public IActionResult Index()
        {
            var groups = _groupService.GetAll();
            return View(groups);
        }
        public IActionResult Details(int id)
        {
            var group = _groupService.GetById(id);
            return View(group);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Group group)
        {
            if (ModelState.IsValid)
            {
                _groupService.Add(group);
                return RedirectToAction("Index");
            }
            return View(group);
        }

        public IActionResult Update(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var group = _groupService.GetById(id);
            if (group == null)
            {
                return NotFound();
            }
            return View(group);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Group group)
        {
            if (ModelState.IsValid)
            {
                _groupService.Update(group);
                return RedirectToAction("Index");
            }
            return View(group);
        }

        public IActionResult Delete(int id)
        {
            if(id == 0)
            {
                return NotFound();
            }

            var group = _groupService.GetById(id);
            if(group == null)
            {
                return NotFound();
            }
            return View(group);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete (Group group)
        {

            _groupService.Remove(group);
            return RedirectToAction("Index");   
        }


    }
}

Jobsway2go.WebUI/Views/Group/Create.cshtml
@model Group

<form method="POST">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Group</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name" class="form-control"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary " style="width:150px">Create</button>
        <a asp-controller="Group" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

Jobsway2go.WebUI/Views/Group/Delete.cshtml
@model Group

<form method="post" asp-action="Delete">
	<input asp-for="Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Are you Sure ?!</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" disabled class="form-control" />
		</div>
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="Group" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

Jobsway2go.WebUI/Views/Group/Index.cshtml
@model IEnumerable<Group>
@{
    ViewData["Title"] = "Index";
}

<div style="margin:40px;">
    <h1> Groups Manager</h1>
    <p>
        <a asp-controller="Group" asp-action="Create" class="btn btn-primary">Create Groups</a>
    </p>
  
    <table class="table table-hover table-bordered" width="100%">
        <thead>
            <tr class="table">
                <th>Group Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>@obj.Name </td>
                    <td>
                        <a class="btn btn-primary btn-sm" asp-controller="Group" asp-action="Update" asp-route-id="@obj.Id">Edit</a>
                        <a class="btn btn-info btn-sm" asp-controller="Group" asp-action="Details" asp-route-id="@obj.Id">Details</a>
                        <a class="btn btn-danger btn-sm" asp-controller="Group" asp-action="Delete" asp-route-id="@obj.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>


</div>

Jobsway2go.WebUI/Views/Group/Update.cshtml
@model Group

<form method="POST" asp-action="Update">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Update Group</h2>
            <hr />
        </div>
        <label asp-for="Id"/>
        <div class="mb-3">
            <label asp-for="Name" class="form-control"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary " style="width:150px">Update</button>
        <a asp-controller="Group" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }